bootstrap.memory_lock: false
cluster.name: elasticsearch
http.port: 9200
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: SANTOSH719-PC
path.data: D:\Softwares\ElasticSearch\data
path.logs: D:\Softwares\ElasticSearch\logs
transport.tcp.port: 9300
